.SILENT:

default:
	echo "This is a python script, to run, use command $ make run"

run:
	python lab3b.py

clean:
	rm -f lab3b_check.txt

dist:
	tar -zcvf lab3b-704637121.tar.gz README lab3b.py Makefile
